export const ADD_DEVPLAN = "ADD_DEVPLAN";
export const DELETE_DEVPLAN = "DELETE_DEVPLAN";
export const LOAD_DEVPLANS_SUCCESS = "LOAD_DEVPLANS_SUCCESS";
export const LOAD_EMPLOYEES_SUCCESS = "LOAD_EMPLOYEES_SUCCESS";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
